const conway={
	"name": "Conway's Game Of Life",
	"version": "0.3",
	"description": "Cellular automata",
	"status": "Under construction, zero cycles old",
	"copyright": "(C) 2026 nitrologic",
	"credit": "Generated by Simon Armstrong, Kimi K2.7",
	"license":{"name": "MIT", "url": "https://opensource.org/licenses/MIT"},
	"repository":{"type": "git", "url": "https://github.com/nitrologic/biblispec"},
	"logic":{
		"untested pixel rule":[
			"const alive = this.getPixel(x, y, readLayer);",
			"const neighbors = this.countNeighbors(x, y, readLayer);",
			"const write = (alive && (neighbors === 2 || neighbors === 3)) || (!alive && neighbors === 3);"
		]
	},
	"shapes":{
		"still": {
			"block": [
				"OO",
				"OO"
			],
			"beehive": [
				".OO.",
				"O..O",
				".OO."
			],
			"loaf": [
				".OO.",
				"O..O",
				".O.O",
				"..O."
			],
			"boat": [
				"OO.",
				"O.O",
				".O."
			]
		},
		"oscillators": {
			"blinker": [
				"...",
				"OOO",
				"..."
			],
			"toad": [
				".OOO",
				"OOO."
			],
			"beacon": [
				"OO..",
				"OO..",
				"..OO",
				"..OO"
			],
			"pulsar": [
				"..OOO...OOO..",
				".............",
				"O....O.O....O",
				"O....O.O....O",
				"O....O.O....O",
				"..OOO...OOO..",
				".............",
				"..OOO...OOO..",
				"O....O.O....O",
				"O....O.O....O",
				"O....O.O....O",
				".............",
				"..OOO...OOO.."
			]
		},
		"spaceships": {
			"glider": [
				".O.",
				"..O",
				"OOO"
			]
		},
		"methuselahs": {
			"rPentomino": [
				".OO",
				"OO.",
				".O."
			],
			"diehard": [
				"......O.",
				"OO......",
				".O...OOO"
			]
		}
	}
}
